web:
  build: .
  command: bundle exec rails server -b 0.0.0.0
  volumes:
    - .:/myapp
  ports:
    - "3000:3000"
  links:
    - db:db
    - redis
db:
  image: postgres
  ports:
    - "5432"

redis:
  image: redis
  ports:
    - "6379"

#sidekiq:
  #build: .
  #command: bundle exec sidekiq
  #links:
    #- db
    #- redis

