production:
  services:
    app:
      git_url: git@github.com:detierno/docker-sample.git
      git_branch: master
      command: bundle exec rails server -p 3000
      build_command: rake db:migrate
      deploy_command: rake db:migrate
      log_folder: /usr/src/app/log
      ports: ["3000:80:443"]
      volumes: ["/tmp:container/tmp_host"]
      restart_on_redeploy: true
      asset_pipeline_precompile: true
  databases:
    - "postgresql"
