production:
  services:
    app:
      git_url: git@github.com:detierno/docker-mysql.git
      git_branch: master
      command: bundle exec rackup -p 3000
      build_command: rake db:migrate
      deploy_command: rake db:migrate
      log_folder: /usr/src/app/log
      ports: ["80:80:443"]
  databases:
    - "postgresql"
