default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password:
  host: <%= ENV['RDF_DB_1_PORT_5432_TCP_ADDR'] %>
  port: <%= ENV['RDF_DB_1_PORT_5432_TCP_PORT'] %>
  pool: 5

development:
  <<: *default
  database: demo_development

test:
  <<: *default
  database: demo_test

production:
  database: <%= ENV['POSTGRES_DATABASE']  %>
  username: <%= ENV['POSTGRES_USERNAME']  %>
  password: <%= ENV['POSTGRES_PASSWORD']  %>
  host: <%= ENV['POSTGRESQL_ADDRESS'] %>
  port: 5432
  pool: 5
