default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password:
  host: <%= ENV['RDF_DB_1_PORT_5432_TCP_ADDR'] %>
  port: <%= ENV['RDF_DB_1_PORT_5432_TCP_PORT'] %>
  pool: 5

development:
  <<: *default
  database: demo_development

test:
  <<: *default
  database: demo_test
